### ISSUE TITLE
As a user, I want to create new todo items so I can keep track of my tasks

### ISSUE THREAD

**Issue by OlgaOrl** [OlgaOrl/todo#1]
- [ ]  Input field is available to enter todo text
- [ ] "Add" button creates a new todo
- [ ] New todos appear at the top of the list
- [ ] Cannot create empty todos

**Comment by OlgaOrl** [comment]
![image](https://github.com/user-attachments/assets/b7f6dbd5-7572-414b-a04f-958f4a13bde9)

**Comment by OlgaOrl** [comment]
![image](https://github.com/user-attachments/assets/0ddce99c-912c-4130-9f0a-dc3381b467f0)
